services:
  - type: web
    name: campusflow-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: campusflow-db
          property: host
      - key: DB_NAME
        fromService:
          type: pserv
          name: campusflow-db
          property: database
      - key: DB_USER
        fromService:
          type: pserv
          name: campusflow-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: campusflow-db
          property: password

  - type: pserv
    name: campusflow-db
    env: postgres
    plan: free # You can choose a different plan on Render
    pversion: "14" # Specify your desired PostgreSQL version
